name: Python Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: chartboost/ruff-action@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Ruff
      run: pip install ruff

    - name: Check code with Ruff
      run: ruff check PycharmProjects/pythonProject7/main.py PycharmProjects/pythonProject7/testing_functions.py

