name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
      - name: Install dependencies
        run: pip install ruff==0.3.3
      - name: Run Ruff
        run: ruff check PycharmProjects/pythonProject7/main.py PycharmProjects/pythonProject7/testing_functions.py
