name: Lint Code Base

on: [push, pull_request]

jobs:
  super-linter:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_FLAKE8: true  # Enable or disable specific linters
          # Add other environment variables as needed

  ruff-lint:
    name: Run Ruff Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
         run: pip install ruff
      - name: Run Ruff
         run: ruff check .
